---
driver:
  name: vagrant
  vm_hostname: setupmyenvhost

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.13.11

verifier:
  name: inspec

platforms:
  - name: tas50/windows_10
    os_type: windows
    transport:
      name: winrm
      elevated: true
    driver:
      customize:
        cpus: 2
        memory: 4096
  - name: tas50/windows_2019
    os_type: windows
    transport:
      name: winrm
      elevated: true
    driver:
      customize:
        cpus: 2
        memory: 4096
  - name: tas50/windows_2016
    os_type: windows
    transport:
      name: winrm
      elevated: true
    driver:
      customize:
        cpus: 2
        memory: 4096
  - name: tas50/windows_2012r2
    os_type: windows
    transport:
      name: winrm
      elevated: true
    driver:
      customize:
        cpus: 2
        memory: 4096
  - name: centos/7

suites:
  - name: default
    run_list:
      - recipe[setupmyenv::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
