---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  product_name: chef
  product_version: latest
  channel: stable

verifier:
  name: inspec

platforms:
  - name: ubuntu/xenial64
  - name: centos/7
  - name: my/win2016
    transport:
      name: winrm
      elevated: true
      customize:
        memory: 6144
      vm_hostname: mywinvm

suites:
  - name: default
    run_list:
      - recipe[mycookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: win-diskd
    run_list:
      - recipe[mycookbook::dskxpnd]
      - recipe[mycookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    driver:
      customize:
        createhd:
          - filename: d:/VMs/disk2.vmdk
            size: 2048
        storagectl:
          - name: IDE Controller
            portcount: 2
        storageattach:
          - storagectl: IDE Controller
            port: 1
            device: 1
            type: hdd
            medium: d:/VMs/disk2.vmdk
    includes:
      - my/win2016
