---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
  network:
    - ["private_network", {ip: "192.168.33.36"}]

transport:
  name: winrm
  elevated: true
  username: 'vagrant'
  password: 'vagrant'
  gui: true

provisioner:
  name: shell

platforms:
  - name: DevOps_Windows2012R2
    os_type: windows

suites:
  - name: windows
    driver:
      vm_hostname: windows
    run_list:
      - recipe[chef-client::delete_validation],recipe[customchefclient]
    attributes:
