---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu/xenial64
  - name: centos/7
  - name: mwrock/Windows2016
    transport:
      name: winrm
      elevated: true
      customize:
        memory: 6144
      vm_hostname: mywinvm

suites:
  - name: default
    run_list:
      - recipe[resourcetest::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: secondisk
    run_list:
      - recipe[resourcetest::default]
    verifier:
      inspec_tests:
        - test/integration/default
    driver:
      customize:
        createhd:
          - filename: d:/VMs/disk2.vdi
            size: 1024
        storagectl:
          - name: IDE
            controller: PIIX4
            portcount: 2
        storageattach:
          - storagectl: IDE
            port: 1
            device: 1
            type: hdd
            medium: d:/VMs/disk2.vdi
