---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64
    verifier:
      attributes:
        is_docker: false
  - name: centos/7
    attributes:
      myattribute: 'something else'

suites:
  - name: default
    run_list:
      - recipe[lazytest::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
